### PR TITLE
Update style post form

### PR DESCRIPTION
**Pull request by NeuralAlchemist**
Updated postform to have vertically resizeable textarea and have scroll bar. Making it autosize according to content inside was not possible without jQuery or some extra js.

Screenshot 2021-05-07 at 16 46 12

### CODE REVIEW

**Comment by eeels22** [comment]
Looks good but perhaps the focus styling could be var(--color-teal) instead of the default blue?

**Review by eeels22 — COMMENTED** [review]
Thanks! Looks good but perhaps the focus styling could be var(--color-teal) instead of the default blue?

**Comment by NeuralAlchemist** [comment]
I had to increase the border size to 2px otherwise the color teal was not standing out as much when in focus
Screenshot 2021-05-10 at 09 29 36
Screenshot 2021-05-10 at 09 29 29
### with 1px border
Screenshot 2021-05-10 at 09 31 45
Screenshot 2021-05-10 at 09 31 40

**Comment by eeels22** [comment]
Thanks Yash, I think 2px with teal looks good, and we have 2px for the focus styling for the login form so it's consistent.

**Review by eeels22 — APPROVED** [review]

**Review by janko101 — APPROVED** [review]

**Pull request merged**
