### PR TITLE
Timelapse and Post Likes

### PR DESCRIPTION
**Pull request by janko101**
# Changes proposed in this pull request
- Adds timelapse for a post.
- Adds timelapse for a comment
- Add/Remove user's like for a specific post

## User Story
As a pet owner, I want to like a post, so that I can express my reaction to it

### CODE REVIEW

**Review by NeuralAlchemist — DISMISSED** [review]
looks good

**Review by deciocandido — DISMISSED** [review]

**Comment by estherchee** [comment]
It looks good to me.

**Review by estherchee — APPROVED** [review]
It looks good to me.

**Review by eeels22 — APPROVED** [review]
Great work!

**Pull request merged**
